/**
 * Email service for sending claim emails via Firebase Cloud Functions
 */

import { getFirebaseAuth } from '@infrastructure/database/firebase';
import { EmailSendingError, UUID } from '@core/types';

/**
 * Interface for email attachment
 */
export interface EmailAttachment {
  content: string; // Base64 encoded content
  filename: string;
  type: string; // MIME type
  disposition: string;
}

/**
 * Interface for email sending request
 */
export interface SendEmailRequest {
  to: string;
  subject: string;
  htmlContent: string;
  textContent?: string;
  claimId: UUID;
  attachments?: EmailAttachment[];
}

/**
 * Email service using Firebase Cloud Functions
 */
export class EmailService {
  private static readonly FUNCTION_URL =
    'https://us-central1-clearclaim2025.cloudfunctions.net/sendClaimEmail';

  /**
   * Send claim email to insurer
   */
  async sendClaimEmail(request: SendEmailRequest): Promise<{ success: boolean; claimId: UUID }> {
    try {
      console.log('📧 Sending email to:', request.to);

      // Get the current user's auth token
      const auth = getFirebaseAuth();
      const currentUser = auth.currentUser;

      if (!currentUser) {
        throw new EmailSendingError('User not authenticated');
      }

      // Get the ID token
      const idToken = await currentUser.getIdToken();
      console.log('✅ Got ID token, calling Cloud Function...');

      // Call the Cloud Function
      const response = await fetch(EmailService.FUNCTION_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${idToken}`,
        },
        body: JSON.stringify(request),
      });

      console.log('📨 Cloud Function response status:', response.status);

      if (!response.ok) {
        const error = await response.json();
        console.error('❌ Cloud Function error:', error);
        throw new EmailSendingError(
          `Failed to send email: ${error.error || response.statusText}`
        );
      }

      const data = await response.json();
      console.log('✅ Email sent successfully:', data);
      return {
        success: true,
        claimId: data.claimId,
      };
    } catch (error) {
      console.error('❌ Email sending error:', error);
      if (error instanceof EmailSendingError) {
        throw error;
      }
      throw new EmailSendingError(
        `Failed to send email: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Format claim email HTML
   */
  formatClaimEmailHTML(
    insuredName: string,
    policyNumber: string,
    insurerName: string,
    emailBody: string
  ): string {
    return `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <style>
      body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
      .container { max-width: 600px; margin: 0 auto; padding: 20px; }
      .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
      .header h1 { margin: 0; font-size: 24px; }
      .content { background: #f9f9f9; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
      .content p { margin: 0 0 15px 0; }
      .footer { text-align: center; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
      .claim-info { background: white; padding: 15px; border-left: 4px solid #667eea; margin: 15px 0; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>Insurance Claim Submission</h1>
        <p>ClearClaim - Automated Insurance Claim Processing</p>
      </div>

      <div class="claim-info">
        <p><strong>Insured Person:</strong> ${insuredName}</p>
        <p><strong>Policy Number:</strong> ${policyNumber}</p>
        <p><strong>Insurance Company:</strong> ${insurerName}</p>
      </div>

      <div class="content">
        ${emailBody.replace(/\n/g, '<br>')}
      </div>

      <div class="footer">
        <p>This email was generated by ClearClaim - Automated Insurance Claim Processing</p>
        <p>&copy; 2025 ClearClaim. All rights reserved.</p>
      </div>
    </div>
  </body>
</html>
    `.trim();
  }
}
